#Change ROKU_DEV_TARGET to your Roku's IP address
#Change DEVPASSWORD to your Roku's developer password
#Change APP_KEY_PASS to the password for your signing key
APPNAME = Odysee Roku App
APPVERSION = 1.0.0
ROKU_DEV_TARGET =
DEVPASSWORD = 
APP_KEY_PASS = 

include ./app.mk
